// 国家队名称中英文映射
export const NATIONAL_TEAM_MAP: Record<string, string> = {
  '墨西哥': 'Mexico',
  '南非': 'South Africa',
  '巴西': 'Brazil',
  '阿根廷': 'Argentina',
  '德国': 'Germany',
  '法国': 'France',
  '英格兰': 'England',
  '西班牙': 'Spain',
  '意大利': 'Italy',
  '荷兰': 'Netherlands',
  '葡萄牙': 'Portugal',
  '比利时': 'Belgium',
  '克罗地亚': 'Croatia',
  '乌拉圭': 'Uruguay',
  '哥伦比亚': 'Colombia',
  '日本': 'Japan',
  '韩国': 'South Korea',
  '澳大利亚': 'Australia',
  '美国': 'USA',
  '加拿大': 'Canada',
  '中国': 'China',
  '瑞士': 'Switzerland',
  '丹麦': 'Denmark',
  '瑞典': 'Sweden',
  '挪威': 'Norway',
  '波兰': 'Poland',
  '捷克': 'Czech Republic',
  '奥地利': 'Austria',
  '塞尔维亚': 'Serbia',
  '罗马尼亚': 'Romania',
  '希腊': 'Greece',
  '土耳其': 'Turkey',
  '俄罗斯': 'Russia',
  '乌克兰': 'Ukraine',
  '威尔士': 'Wales',
  '苏格兰': 'Scotland',
  '爱尔兰': 'Ireland',
  '智利': 'Chile',
  '秘鲁': 'Peru',
  '厄瓜多尔': 'Ecuador',
  '委内瑞拉': 'Venezuela',
  '巴拉圭': 'Paraguay',
  '尼日利亚': 'Nigeria',
  '喀麦隆': 'Cameroon',
  '加纳': 'Ghana',
  '塞内加尔': 'Senegal',
  '摩洛哥': 'Morocco',
  '突尼斯': 'Tunisia',
  '埃及': 'Egypt',
  '阿尔及利亚': 'Algeria',
  '科特迪瓦': 'Ivory Coast',
  '伊朗': 'Iran',
  '伊拉克': 'Iraq',
  '沙特': 'Saudi Arabia',
  '沙特阿拉伯': 'Saudi Arabia',
  '卡塔尔': 'Qatar',
  '阿联酋': 'United Arab Emirates',
};

// 英超球队名称映射
export const PREMIER_LEAGUE_MAP: Record<string, string> = {
  '曼城': 'Manchester City',
  '利物浦': 'Liverpool',
  '曼联': 'Manchester United',
  '阿森纳': 'Arsenal',
  '切尔西': 'Chelsea',
  '热刺': 'Tottenham',
  '托特纳姆热刺': 'Tottenham',
  '纽卡斯尔': 'Newcastle',
  '纽卡斯尔联': 'Newcastle',
  '阿斯顿维拉': 'Aston Villa',
  '西汉姆': 'West Ham',
  '西汉姆联': 'West Ham',
  '布莱顿': 'Brighton',
  '水晶宫': 'Crystal Palace',
  '狼队': 'Wolverhampton',
  '伯恩茅斯': 'Bournemouth',
  '富勒姆': 'Fulham',
  '布伦特福德': 'Brentford',
  '诺丁汉森林': 'Nottingham Forest',
  '埃弗顿': 'Everton',
  '伯恩利': 'Burnley',
  '谢菲尔德联': 'Sheffield United',
  '卢顿': 'Luton',
  '莱斯特城': 'Leicester',
  '利兹联': 'Leeds',
  '南安普顿': 'Southampton',
};

// 西甲球队名称映射
export const LA_LIGA_MAP: Record<string, string> = {
  '皇马': 'Real Madrid',
  '皇家马德里': 'Real Madrid',
  '巴萨': 'Barcelona',
  '巴塞罗那': 'Barcelona',
  '马竞': 'Atletico Madrid',
  '马德里竞技': 'Atletico Madrid',
  '塞维利亚': 'Sevilla',
  '皇家社会': 'Real Sociedad',
  '毕尔巴鄂竞技': 'Athletic Club',
  '毕尔巴鄂': 'Athletic Club',
  '比利亚雷亚尔': 'Villarreal',
  '皇家贝蒂斯': 'Real Betis',
  '贝蒂斯': 'Real Betis',
  '瓦伦西亚': 'Valencia',
  '赫罗纳': 'Girona',
  '奥萨苏纳': 'Osasuna',
  '塞尔塔': 'Celta Vigo',
  '马略卡': 'Mallorca',
  '拉斯帕尔马斯': 'Las Palmas',
  '赫塔菲': 'Getafe',
  '阿拉维斯': 'Alaves',
  '加的斯': 'Cadiz',
  '格拉纳达': 'Granada',
};

// 意甲球队名称映射
export const SERIE_A_MAP: Record<string, string> = {
  '国际米兰': 'Inter',
  '国米': 'Inter',
  'AC米兰': 'AC Milan',
  '米兰': 'AC Milan',
  '尤文图斯': 'Juventus',
  '尤文': 'Juventus',
  '那不勒斯': 'Napoli',
  '罗马': 'AS Roma',
  '拉齐奥': 'Lazio',
  '亚特兰大': 'Atalanta',
  '佛罗伦萨': 'Fiorentina',
  '都灵': 'Torino',
  '博洛尼亚': 'Bologna',
  '蒙扎': 'Monza',
  '乌迪内斯': 'Udinese',
  '萨索洛': 'Sassuolo',
  '热那亚': 'Genoa',
  '卡利亚里': 'Cagliari',
  '弗洛西诺内': 'Frosinone',
  '莱切': 'Lecce',
  '萨勒尼塔纳': 'Salernitana',
  '维罗纳': 'Verona',
  '恩波利': 'Empoli',
};

// 德甲球队名称映射
export const BUNDESLIGA_MAP: Record<string, string> = {
  '拜仁': 'Bayern Munich',
  '拜仁慕尼黑': 'Bayern Munich',
  '多特蒙德': 'Dortmund',
  '勒沃库森': 'Bayer Leverkusen',
  '莱比锡': 'RB Leipzig',
  '莱比锡红牛': 'RB Leipzig',
  '法兰克福': 'Eintracht Frankfurt',
  '斯图加特': 'Stuttgart',
  '沃尔夫斯堡': 'Wolfsburg',
  '门兴': 'Monchengladbach',
  '门兴格拉德巴赫': 'Monchengladbach',
  '弗赖堡': 'Freiburg',
  '柏林联合': 'Union Berlin',
  '奥格斯堡': 'Augsburg',
  '美因茨': 'Mainz',
  '科隆': 'FC Koln',
  '不莱梅': 'Werder Bremen',
  '霍芬海姆': 'Hoffenheim',
  '海登海姆': 'Heidenheim',
  '达姆施塔特': 'Darmstadt',
  '波鸿': 'Bochum',
};

// 法甲球队名称映射
export const LIGUE_1_MAP: Record<string, string> = {
  '巴黎圣日耳曼': 'Paris Saint Germain',
  '大巴黎': 'Paris Saint Germain',
  'PSG': 'Paris Saint Germain',
  '马赛': 'Marseille',
  '摩纳哥': 'Monaco',
  '里昂': 'Lyon',
  '里尔': 'Lille',
  '尼斯': 'Nice',
  '雷恩': 'Rennes',
  '朗斯': 'Lens',
  '蒙彼利埃': 'Montpellier',
  '斯特拉斯堡': 'Strasbourg',
  '南特': 'Nantes',
  '图卢兹': 'Toulouse',
  '布雷斯特': 'Brest',
  '兰斯': 'Reims',
};

// 其他联赛球队名称映射
export const OTHER_LEAGUES_MAP: Record<string, string> = {
  // 葡超
  '本菲卡': 'Benfica',
  '波尔图': 'FC Porto',
  '里斯本竞技': 'Sporting CP',
  // 荷甲
  '阿贾克斯': 'Ajax',
  '费耶诺德': 'Feyenoord',
  'PSV': 'PSV',
  '埃因霍温': 'PSV',
  // 沙特联赛
  '利雅得新月': 'Al-Hilal Saudi FC',
  '新月': 'Al-Hilal Saudi FC',
  '吉达联合': 'Al-Ittihad FC',
  '联合': 'Al-Ittihad FC',
  '利雅得胜利': 'Al-Nassr',
  '胜利': 'Al-Nassr',
  '吉达阿赫利': 'Al-Ahli Jeddah',
  '阿赫利': 'Al-Ahli Jeddah',
  '卡迪西亚': 'Al-Qadisiyah FC',
  '阿尔卡迪西亚': 'Al-Qadisiyah FC',
  '达曼协作': 'Al-Ettifaq',
  '协作': 'Al-Ettifaq',
  '利雅得青年': 'Al Shabab',
  '青年人': 'Al Shabab',
  '布赖代合作': 'Al Taawon',
  '合作': 'Al Taawon',
  '阿尔奥罗巴': 'Al Orubah',
  '欧鲁巴': 'Al Orubah',
  '阿尔利雅德': 'Al Riyadh',
  '哈萨征服': 'Al-Fateh',
  '征服': 'Al-Fateh',
  '阿尔拉亚恩': 'Al-Raed',
  '拉亚恩': 'Al-Raed',
  '费哈': 'Al-Fayha',
  '阿尔费哈': 'Al-Fayha',
  '达马克': 'Damac',
  '阿尔霍利德': 'Al Kholood',
  '阿尔科里亚': 'Al Kholood',
  '阿尔韦赫达': 'Al Wehda Club',
  '韦赫达': 'Al Wehda Club',
  '阿尔奥克杜德': 'Al Okhdood',
  '阿克杜德': 'Al Okhdood',
  '吉达国民': 'Al-Ahli Jeddah',
  '萨伊哈特赫利杰': 'Al Khaleej Saihat',
  '赫利杰': 'Al Khaleej Saihat',
  // 其他中东联赛
  '阿尔艾因': 'Al-Ain',
};

// 合并所有映射
export const TEAM_NAME_MAP: Record<string, string> = {
  ...NATIONAL_TEAM_MAP,
  ...PREMIER_LEAGUE_MAP,
  ...LA_LIGA_MAP,
  ...SERIE_A_MAP,
  ...BUNDESLIGA_MAP,
  ...LIGUE_1_MAP,
  ...OTHER_LEAGUES_MAP,
};
